export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as TrustedBy } from './TrustedBy'
export { default as Products } from './Products'
export { default as Blog } from './Blog'
export { default as FAQ } from './FAQ'
export { default as CTA } from './CTA'
export { default as Footer } from './Footer'
